### ISSUE TITLE
WireMock server not starting from Spock test

### ISSUE THREAD

**Issue by spartanhooah** [phxql/wiremock-junit5#3]
I'm working on upgrading a Spring Boot API from Spock 1.3 to 2.0, which requires migrating JUnit dependencies from 4 to 5, so I found this project which sounds great (we were using the okhttp mock server, but it's still dependent on JUnit 4). The class under test takes a domain and port in its constructor (to account for different environments), like this:

```
public SomeService(@Value("${app.domains.internal}") final String internalDomain) {
    this.serviceWebClient = WebClient.builder().baseUrl(internalDomain + "/foo/bar").build();
}
```

So in the test, I have

```
class SomeServiceTest extends Specification {
    @RegisterExtension
    WireMockExtension wireMock = new WireMockExtension()

    SomeService service
    
    def setup() {
        service = new SomeService("http://localhost${(wireMock as WireMockServer).port()}")
    }
    
    def "test the service"() {
        given:
        wireMock.wireMock.givenThat(
            get(urlPathEqualTo("/foo/bar"))
            .willReturn(aResponse())
        
        when:
        service.call()
        
        then:
        true
    }
}
```

But I get `Not listening on HTTP port. Either HTTP is not enabled or the WireMock server is stopped.` What step am I missing?

**Comment by phxql** [comment]
Hi, i have no idea how Spock interacts with JUnit 5.

The library has a hook, which is called by JUnit 5, see [here](https://github.com/phxql/wiremock-junit5/blob/08c5b9902e1e465297269ad578d40cef573529c1/src/main/java/de/mkammerer/wiremock/WireMockExtension.java#L92). JUnit calls this hook when a test is run. This starts the Wiremock server. You could add a breakpoint and check if this is called when run your Spock tests run. If it isn't called, then this library is not compatible with Spock. In that case you could call `beforeEach` manually. Don't forget to call `afterEach` after the test.

**Comment by phxql** [comment]
Maybe the call to `port()` in your setup method happens to soon. Try to move the setup code in the `def "test the service"() {`. If this fixes the problem, try to use `@BeforeEach` from JUnit 5. I don't know the order in which Spock executes those methods.

**Comment by spartanhooah** [comment]
Yup, it indeed looks like Spock isn't calling JUnit's before/after methods. I added `wireMock.start()` and `wireMock.stop()` to `setupSpec()` and `cleanupSpec()`, which are Spock's equivalents to `beforeAll` and `afterAll` and that seemed to fix the server starting up. Thanks for the idea!
